name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate || echo "Failed to activate virtual environment"
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest fairscale matplotlib
        pip install --upgrade "jax[cpu]" optax dm-haiku
        pip install -e .
        pip install whisper
        pip list
        pip show whisper
        pytest || (echo "Tests failed. Printing error log:"; cat pytest.log)
      env:
        PYTHONUNBUFFERED: 1
    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-log
        path: pytest.log

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies and run tests
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest fairscale matplotlib
        pip install --upgrade "jax[cpu]" optax dm-haiku
        pip install -e .
        pip install whisper
        pip list
        pip show whisper
        pytest || (echo "Tests failed. Printing error log:"; type pytest.log)
      env:
        PYTHONUNBUFFERED: 1
    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-log-windows
        path: pytest.log

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies and run tests
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest fairscale matplotlib
        pip install --upgrade "jax[cpu]" optax dm-haiku
        pip install -e .
        pip install whisper
        pip list
        pip show whisper
        pytest || (echo "Tests failed. Printing error log:"; cat pytest.log)
      env:
        PYTHONUNBUFFERED: 1
    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-log-macos
        path: pytest.log
