name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Install JAX
      run: |
        pip install --upgrade "jax[cpu]"
    - name: Install optax
      run: pip install optax
    - name: List installed packages
      run: pip list
    - name: Run tests
      run: |
        pytest
    - name: Deactivate virtual environment
      run: deactivate
      if: always()

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        .\venv\Scripts\Activate.ps1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Install JAX for Windows
      run: |
        pip install --upgrade "jax[cpu]"
    - name: Install optax
      run: pip install optax
    - name: List installed packages
      run: pip list
    - name: Run tests
      run: |
        pytest
    - name: Deactivate virtual environment
      run: deactivate
      if: always()

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Install JAX
      run: |
        pip install --upgrade "jax[cpu]"
    - name: Install optax
      run: pip install optax
    - name: List installed packages
      run: pip list
    - name: Run tests
      run: |
        pytest
    - name: Deactivate virtual environment
      run: deactivate
      if: always()
