name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Upgrade setuptools
      run: |
        python -m pip install --upgrade setuptools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest scipy
    - name: Install JAX
      run: |
        pip install --upgrade "jax[cpu]"
    - name: Install matplotlib
      run: |
        pip install matplotlib
    - name: Print installed packages
      run: |
        pip list
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Print PYTHONPATH
      run: |
        echo $PYTHONPATH
    - name: Run tests
      run: |
        pytest -v -m "not jax_unsupported"

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Upgrade setuptools
      run: |
        python -m pip install --upgrade setuptools
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest scipy
    - name: Install matplotlib
      run: |
        pip install matplotlib
    - name: Print installed packages
      run: |
        pip list
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$env:PYTHONPATH;${{ github.workspace }}\src" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Print PYTHONPATH
      run: |
        echo $env:PYTHONPATH
    - name: Run tests
      run: |
        pytest -v -m "not jax_unsupported"

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Upgrade setuptools
      run: |
        python -m pip install --upgrade setuptools
    - name: Ensure pip is installed
      run: |
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip
    - name: Install Cython
      run: |
        pip install Cython
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest scipy
    - name: Install JAX
      run: |
        pip install --upgrade "jax[cpu]"
    - name: Install matplotlib
      run: |
        pip install matplotlib
    - name: Print installed packages
      run: |
        pip list
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}/src" >> $GITHUB_ENV
    - name: Print PYTHONPATH
      run: |
        echo $PYTHONPATH
    - name: Run tests
      run: |
        pytest -v -m "not jax_unsupported"
